#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
---
apiVersion: v1
data: #@ data.values.tap.credentials.certificate
kind: Secret
metadata:
  name: tls
  namespace: learningcenter
type: kubernetes.io/tls
---
apiVersion: v1
data: #@ data.values.tap.credentials.certificate
kind: Secret
metadata:
  name: tls
  namespace: #@ data.values.tls.namespace
type: kubernetes.io/tls