#@data/values

#@overlay/match-child-defaults missing_ok=True
---
tap:
  devNamespace: tap-dev

  domains:
    learningCenter: learningcenter.y-compiles.com
    knative: apps.y-compiles.com
    appliveview:
      host: appliveview.y-compiles.com
  supplychain:
    gitops:
      repo:
        prefix: ssh://git@github.com/ynamadi/
        branch: main
        commit:
          message: supply-chain-commit
      user:
        name: ynamadi
        email: ynamadi@vmware.com
      secret: git-ssh

domain: y-compiles.com
tls:
  secretName: tls
  namespace: tanzu-system-ingress